name: Release .NET Core 6 API

# 當標籤被推送時觸發（例如 v1.0.0）
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 壓縮 VIS_API 資料夾
      - name: Create Release Package
        run: |
          mkdir -p release
          zip -r release/VIS_API-${{ github.ref_name }}.zip VIS_API

      # Step 3: 創建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This release contains the latest version of the VIS_API project.
          draft: false
          prerelease: false

      # Step 4: 上傳壓縮包到 Release
      - name: Upload Release Package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/VIS_API-${{ github.ref_name }}.zip
          asset_name: VIS_API-${{ github.ref_name }}.zip
          asset_content_type: application/zip
