name: Release VIS_API

# 當標籤被推送時觸發（例如 v1.0.0）
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      # Step 1: 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 設置 .NET 環境
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0

      # Step 3: 使用 MSBuild 構建專案
      - name: Build VIS_API
        run: |
          msbuild VIS_API/VIS_API.sln /t:Restore /p:Configuration=Release
