name: Build and Release VIS_API

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    env:
      Solution_Name: VIS_API/VIS_API.sln  # 設置正確的解決方案路徑
      Configuration: Release             # 構建配置

    steps:
      # Step 1: 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 設置 .NET 環境
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0

      # Step 3: 使用 MSBuild 構建專案
      - name: Build Solution
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
