name: Release .NET Core 6 API

# 當標籤被推送時觸發
on:
  push:
    tags:
      - 'v*'  # 只監控符合 vX.X.X 格式的標籤

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 壓縮 VIS_API 資料夾
      - name: Package VIS_API
        run: |
          zip -r VIS_API-${{ github.ref_name }}.zip VIS_API

      # Step 3: 創建 Release 並上傳壓縮包
      - name: Create and Upload GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release contains the latest version of the VIS_API project.
          artifacts: VIS_API-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
