name: Build, Package, and Deploy to Remote Server

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: 設置 .NET 環境
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Step 3: 恢復依賴
      - name: Restore dependencies
        run: dotnet restore VIS_API/VIS_API.sln

      # Step 4: 發布應用
      - name: Publish application
        run: dotnet publish VIS_API/VIS_API.sln --configuration Release --output VIS_API_Publish

      # Step 5: 壓縮發布檔
      - name: Package published files
        run: |
          Compress-Archive -Path VIS_API_Publish/* -DestinationPath VIS_API_Publish-v${{ github.ref_name }}.zip

      # Step 6: 設置 SSH 連接
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 7: 傳輸檔案到遠端伺服器
      - name: Upload files to server
        run: |
          scp -v -P -o StrictHostKeyChecking=no 2762 VIS_API_Publish-v${{ github.ref_name }}.zip dek@59.125.31.88:C:/temp/

      # Step 8: 解壓並部署到目標目錄
      - name: Deploy to target directory
        run: |
          ssh -p 2762 dek@59.125.31.88 "
          mkdir -p D:/API_Release;
          powershell -Command 'Expand-Archive -Path C:/temp/VIS_API_Publish-v${{ github.ref_name }}.zip -DestinationPath D:/API_Release -Force';
          "
    
