name: Build and Publish .NET Core App

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      # Step 1: 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: 設置 .NET 環境
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Step 3: 恢復依賴
      - name: Restore dependencies
        run: dotnet restore VIS_API/VIS_API.sln

      # Step 4: 發布應用
      - name: Publish application
        run: dotnet publish VIS_API/VIS_API.sln --configuration Release --output VIS_API_Publish


      # Step 5: 壓縮發布檔
      - name: Package published files
        run: |
          Compress-Archive -Path VIS_API_Publish/* -DestinationPath VIS_API_Publish-v${{ github.ref_name }}.zip

      # Step 6: 上傳發布檔作為 Artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VIS_API_Publish
          path: VIS_API_Publish-v${{ github.ref_name }}.zip

      # Step 7: 創建 GitHub Release 並上傳壓縮包
      - name: Create and Upload GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes
            - This release contains the published application files.
          artifacts: VIS_API_Publish-v${{ github.ref_name }}.zip
          draft: false
          prerelease: false
